### ISSUE TITLE
PHOTO

### ISSUE THREAD

**Issue by mmarteen1** [RYUUSEiiSTAR/produce-sorter#1]
Hello
Just to inform you, Hyewons photo is missing. I know this might not matter, but please; I JUST CAN'T STAND IT. 
Thank you for taking the time to read this

**Comment by RYUUSEiiSTAR** [comment]
Hey! Thanks for letting me know! For some reason the privacy settings on her photo are a bit messed up. I might just re-upload it at this rate haha

**Comment by RYUUSEiiSTAR** [comment]
okay this issue should be fixed and I've updated to include iz*one :)
